### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '=' in /var/www/dokuwiki/lib/plugins/codeprettify/syntax/code.php on line 161

### ISSUE THREAD

**Issue by kissle** [ssahara/dw-plugin-codeprettify#12]
Hi,

I tried to add this plugin to my dokuwiki running on Ubuntu 16.04. but it is causing an error, stopping dokuwiki. Only solution is to manualy remove the plugin from dokuwiki/lib/plugins

Apache2 errorlog:
`PHP Parse error:  syntax error, unexpected '=' in /var/www/dokuwiki/lib/plugins/codeprettify/syntax/code.php on line 161`

regards,
kissle

**Comment by ssahara** [comment]
Hi @kissle 
You are encouraged to upgrade to PHP 7.1 or later

**Comment by iokhahon** [comment]
I hit the same issue, I upgraded PHP from 7.0 to 7.2 and even after clearing the cache and refreshing the page I still had the same problem. No pages would display (so could not access the admin functions), I had to manually delete the plugin from the plugins directory.

**Comment by ssahara** [comment]
Hi @iokhahon 
Could you show me the webserver errorlog? it will help me for trouble shooting.

**Comment by christian1656** [comment]
Hi,
i also added this plugin to my dokuwiki running on a raspberry. Therefore, I used the debian package which also adds an apache server. After adding codeprettify plugin, dokuwiki stopped working.

So I deleted everything and installed dokuwiki with a nginx server manually. Unfortunately, dokuwiki stop working again after installing codeprettify - here's the errorlog from nginx:
`2019/04/28 11:47:22 [error] 16624#16624: *216 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '=' in /var/www/dokuwiki-2018-04-22b/lib/plugins/codeprettify/syntax/code.php on line 161" while reading upstream, client: 10.0.0.215, server: crwiki, request: "GET /doku.php?id=start&do=admin HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "10.0.0.210", referrer: "http://10.0.0.210/doku.php?id=start"`

In the meanwhile I'm using the old version from 2017 which fits to my needs and works perfect.

**Comment by ssahara** [comment]
**Since PHP 7.1.x**, the shorthand array syntax (`[]`) may now be used to destructure arrays for assignments, as an alternative to the existing `list()` syntax, which is still supported.

Here is a patch to make PHP the plugin 7.0 compatible:
```` diff
$ diff -up code.php.orig code.php
--- code.php.orig       2019-03-09 09:07:09.776953928 +0900
+++ code.php    2019-04-29 10:16:09.017701630 +0900
@@ -158,7 +158,7 @@ class syntax_plugin_codeprettify_code ex
     {
         switch ($state) {
             case DOKU_LEXER_ENTER:
-                [$params, $title] = explode('|', substr($match, 5, -1));
+                list($params, $title) = explode('|', substr($match, 5, -1));

                 // title parameter
                 if ($title) {
@@ -210,7 +210,7 @@ class syntax_plugin_codeprettify_code ex
     {
         if ($format == 'metadata') return false;
         if (empty($data)) return false;
-        [$state, $args] = $data;
+        list($state, $args) = $data;

         switch ($state) {
             case 'div_open':
````

**Comment by ssahara** [comment]
The code-prettifier plugin for DokuWiki has updated on **2019-04-29**, for convenience legacy PHP 7.0.x users
