### ISSUE TITLE
indented code blocks

### ISSUE THREAD

**Issue by Jody5** [ssahara/dw-plugin-codeprettify#5]
Line numbers are not properly displayed when the code block is indented, like in this example:

```
<Code linenums:8>
a
b
c
d
</Code>
  * bla <Code linenums:8>
a
b
c
d
</Code>
    - bla <Code linenums:8>
a
b
c
d
</Code>
```
![codeprettify](https://cloud.githubusercontent.com/assets/24608139/21265233/cb40e3dc-c3a0-11e6-8b89-6f35264e0de3.jpg)

**Comment by ssahara** [comment]
Hi @Jody5 ,
Thanks for informed me on this issue.
Line numbers in Indented block should be displayed better since release 2017-07-04
